### ISSUE TITLE
autoLayout animation

### ISSUE THREAD

**Issue by CharlinFeng** [jhurray/JHChainableAnimations#12]
thank you for this powerful frameworks!

i have some questions:

1.chainAnim with autoLaytou is useless,e.g.:
self.redView.makeConstraint(self.leftMarginC,100).animate(2.0f);  //do not has any effects

2.cloud add duratiion for each chain? e.g.:
self.redView.moveX(100).duration(1.5f).thenAfter.moveY(100).duration(.8f).animat;

3.i could not understand the diff between wait/delay and thenAfter? 

thank you!

**Comment by draveness** [comment]
3 i could not understand the diff between wait/delay and thenAfter?

`wait` is just the same as `delay`.

```
-(JHChainableTimeInterval)delay {
    JHChainableTimeInterval chainable = JHChainableTimeInterval(t) {

        for (CAAnimation *aGroup in self.JHAnimationGroups) {
            t+=aGroup.duration;
        }
        CAAnimationGroup *group = [self.JHAnimationGroups lastObject];
        group.beginTime = CACurrentMediaTime() + t;

        return self;
    };
    return chainable;
}

-(JHChainableTimeInterval)wait {
    JHChainableTimeInterval chainable = JHChainableTimeInterval(t) {

        return self.delay(t);
    };
    return chainable;
}
```

`thenAfter` is a method when you use multiple animations in one line of code. You should use `thenAfter`  instead of `animate` like this:

```
view.moveX(10.0).thenAfter(2.0).moveY(10.0).animate(1.0)
```

`view` will move x in two seconds **and then** move y in one second.

You are not supposed to write code like this:

```
// WRONG
view.moveX(10.0).animate(2.0).moveY(10.0).animate(1.0)
```

When you use multiple animations one by one, you should use `thenAfter` instead of  `animate`(`moveX(10.0).thenAfter(2.0)`) except the last animation(`moveY(10.0).animate(1.0)`).

**Comment by jhurray** [comment]
@nsdictionary 

1) I will fix this. I am traveling at the moment and have limited time. For now use the transform methods. those are tested and will work. They also will work with effects, unlike the constraint animations

2) thenAfter(t) should take a time period for the animations before it. I dont want to add a duration property because that will begin to get confusing. 

3) As @Draveness said  wait and delay are the same thing. wait is just more conversational and easy to read while delay is more similar to apples API.
